#!/bin/bash

# Script to generate Supabase JWT tokens for local Docker development
# This generates anon and service_role JWTs based on your JWT_SECRET

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default JWT secret (can be overridden via argument)
JWT_SECRET="${1:-super-secret-jwt-token-change-me-in-prod}"

echo -e "${YELLOW}Generating JWT tokens with secret: ${JWT_SECRET}${NC}"
echo ""

# Function to generate JWT
# Args: $1 = role (anon or service_role), $2 = secret
generate_jwt() {
  local role=$1
  local secret=$2
  local iat=$(date +%s)
  local exp=$((iat + 315360000)) # ~10 years from now

  # Create JWT header (base64url encoded)
  header=$(echo -n '{"alg":"HS256","typ":"JWT"}' | base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')

  # Create JWT payload (base64url encoded)
  payload=$(echo -n "{\"role\":\"$role\",\"iss\":\"supabase\",\"iat\":$iat,\"exp\":$exp}" | base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')

  # Create signature
  signature=$(echo -n "${header}.${payload}" | openssl dgst -sha256 -hmac "$secret" -binary | base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')

  # Combine to create JWT
  echo "${header}.${payload}.${signature}"
}

# Generate anon key
ANON_KEY=$(generate_jwt "anon" "$JWT_SECRET")
echo -e "${GREEN}ANON_KEY:${NC}"
echo "$ANON_KEY"
echo ""

# Generate service role key
SERVICE_ROLE_KEY=$(generate_jwt "service_role" "$JWT_SECRET")
echo -e "${GREEN}SERVICE_ROLE_KEY:${NC}"
echo "$SERVICE_ROLE_KEY"
echo ""

# Optionally create/update .env file
if [ "$2" == "--write-env" ]; then
  # Check if --docker flag is present
  if [ "$3" == "--docker" ]; then
    ENV_FILE=".env.docker"
  else
    ENV_FILE=".env"
  fi
  echo -e "${YELLOW}Writing keys to ${ENV_FILE}...${NC}"

  # Create .env with the generated keys
  cat > "$ENV_FILE" << EOF
# Docker Local Development Environment
# Generated by scripts/generate-jwt-keys.sh
# DO NOT commit this file to version control

# Supabase Configuration (Local Docker Stack)
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
SUPABASE_INTERNAL_URL=http://kong:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# JWT Secret (must match docker-compose.yml)
JWT_SECRET=${JWT_SECRET}

# App Configuration
NEXT_PUBLIC_APP_URL=http://localhost:8000
NODE_ENV=production

# Optional: OpenAI (for transcript field extraction)
OPENAI_API_KEY=

# Optional: API URLs
NEXT_PUBLIC_API_URL=http://localhost:8000/api
NEXT_PUBLIC_API_BASE_URL_CAMPAIGN=

# Optional: Analytics / Telemetry
NEXT_PUBLIC_POSTHOG_KEY=
NEXT_PUBLIC_POSTHOG_HOST=https://us.i.posthog.com

# Optional: AWS (used by audio routes if you enable S3 storage)
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=ap-south-1
AWS_S3_BUCKET=

# Trillet Evals Configuration
TRILLET_EVALS_MASTER_KEY=local-dev-master-key-change-in-production
TRILLET_API_URL=https://api.trillet.ai
EOF

  echo -e "${GREEN}✓ ${ENV_FILE} created successfully!${NC}"
  echo ""
  echo -e "${YELLOW}Next steps:${NC}"
  echo "1. Review and update ${ENV_FILE} with your specific configuration"
  echo "2. Run: docker-compose down"
  echo "3. Run: docker-compose up -d --build"
  echo ""
fi
